### PR TITLE
Adding Tests for cDscDiagnostics Module

### PR DESCRIPTION
**Pull request by ArtWDrahn**
Given I wanted to change some of the functions to expose them to the public, correct some of the logic that exists in the module, and learn Pester I figured this was a good module to write tests for. This should cover all functions except two, Get-WinEvent and Enable-DscEventLog.  Enable-DscEventLog wasn't tested because I couldn't figure out a good way (without modifying the function to mock wevtutil.  I'm sure someone smarter then me will know a good way to test this.  Get-WinEvent wasn't tested because I couldn't figure out how to mock the wrapper instead of the specific module.

This is also written to test the master branch as written.  So it does not include any of my modifications to Test-DscEventLogStatus or Enable-DscEventLog, these tests will need to be rewritten if those changes are going to be taken.

Completely open to feedback as this is the first real dive into Pester.

### CODE REVIEW

**Comment by dlwyatt** [comment]
Sorry that this has sat here for so long.  I'm getting ready to merge it now, but when I check out the PR and run the tests, I get several failures:

```
Describing Get-AllGroupedDscEvents
    Context Get-AllDscEvents returns null
    [+] should call Log 74ms
    [+] should call Get-DscLatestJobId 8ms
    [+] should return null 8ms
    Context Get-AllDscEvents returns events
    [-] Error occurred in Context block 302ms
        You cannot call a method on a null-valued expression.
        At line:30 char:5
    Context Cached Events
    [-] Error occurred in Context block 152ms
        You cannot call a method on a null-valued expression.
        At line:30 char:5
Describing Get-SingleDscOperation
    Context Get-AllGroupedDscEvents is empty
    [+] should return empty 132ms
    Context JobId is Passed but its not found
    [+] should return empty 72ms
    Context JobId is passed and found
    [+] should have called Get-SingleDscOperation 77ms
Describing Split-SingleDscGroupedRecord
    Context Passed an bad DSC record
    [-] Error occurred in Context block 102ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
    Context Passing a Warning
    [-] Error occurred in Context block 70ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
    Context Passing an Operational Log
    [-] Error occurred in Context block 46ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
    Context Passing a Debug Log
    [-] Error occurred in Context block 45ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
    Context Passing a Verbose Log
    [-] Error occurred in Context block 58ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
    Context Passing an Analytic Log
    [-] Error occurred in Context block 44ms
        The value supplied is not valid, or the property is read-only. Change the value, and then try again.
        At C:\Users\dlwya_000\Documents\GitHub\dsc\Tooling\cDscDiagnostics\cDscDiagnostics.psm1:533 char:35
```

I'll look through these and see if I can figure out what's going on, as time allows (possibly this weekend.)

**Comment by ArtWDrahn** [comment]
Strange I ran it again on a clean computer that I didn't develop on and it worked fine. I've found when I run into similar things restarting the PowerShell instance ended up fixing the problem. Let me know if you find something.

**Comment by dlwyatt** [comment]
The first two errors (method on a null-valued expression) can be solved with an extra mock, so it's not dependent on the contents of the event log where the tests are run.

Those "property is not valid" errors from New-Object have me scratching my head.  I don't know what causes them, but ditching the -Property hashtable and just assigning values to the properties after it's constructed work fine.  I'll merge this PR and then add my changes to get the tests working, and we can go from there.  :)

**Comment by ArtWDrahn** [comment]
OK sounds good, sorry for the extra work. Look forward to seeing the changes so I can get a handle on what went wrong.

**Pull request merged**
